### ISSUE TITLE
Cannot GET /tx_explorer

### ISSUE THREAD

**Issue by amplicade** [bigchaindb/kyber#11]
Hi,

I'm trying to access the client examples (here tx_explorer) on http://localhost:33000/tx_explorer. But the browser says `Cannot GET /tx_explorer`

Am I missing a configuration? I executed `make` and `docker-compose up` right after cloning the repository.

Thanks.
Tac

**Comment by jmavila** [comment]
Same issue here. I guess docs are missing some instructions or the examples are not working anymore...

**Comment by diminator** [comment]
Hi @TAC911 @jmavila 

I will be revamping these examples with the new boilerplate code:
https://github.com/bigchaindb/bigchaindb-react-redux-boilerplate

This should make it really easy and lightweight to spin up apps.
Stay tuned and feel free to check out the boilerplate (comments/suggestions are more than welcome!)

**Comment by amplicade** [comment]
Hi @diminator. Thanks sounds great. I guess this one will be using BigchainDB v1.0 and makes use of the Javascript driver? Looking forward for the use-cases to be migrated / developed. When can we expect the first ones? 

Just a short note: I just installed it now and it works. Just noticed that logging out and in again requires entering the whole passphrase. An option to login with password would be good.

**Comment by diminator** [comment]
Indeed, it's in sync with 1.0 and the latest driver (@v1.0)
also note that it automatically syncs up the store through the websocket API

I'm building some use cases for customers as we speak, and will push updates to the boilerplate in time
> An option to login with password would be good.


you can use a self-made password instead of the brain-wallet passphrase ofc (type in yourself and don't use the generate button)

**Comment by jmavila** [comment]
Thanks for the feedback @diminator ! I'm looking forward to checking it :+1:

**Comment by ttmc** [comment]
This repository (bigchaindb/kyber) contains examples that worked with older versions of BigchainDB, but the stuff in this repository hasn't been maintained and the examples almost certainly won't work with newer versions of BigchainDB. Therefore we are closing all the old issues, marking the repo as old/not-supported, and archiving the repo. You can find newer examples in other places.
