### ISSUE TITLE
Can't run docker-compose, trying to load wrong Docker file

### ISSUE THREAD

**Issue by nmarcetic** [bigchaindb/kyber#14]
Stack trace 
```
Building bdb-server
ERROR: Cannot locate specified Dockerfile: Dockerfile-dev
Makefile:4: recipe for target 'build' failed
make: *** [build] Error 1
```

There is no Dockerfile-dev

**Comment by ttmc** [comment]
This repository (bigchaindb/kyber) contains examples that worked with older versions of BigchainDB, but the stuff in this repository hasn't been maintained and the examples almost certainly won't work with newer versions of BigchainDB. Therefore we are closing all the old issues, marking the repo as old/not-supported, and archiving the repo. You can find newer examples in other places.
