### ISSUE TITLE
make errors on every bash installation command

### ISSUE THREAD

**Issue by TheKocka8** [bigchaindb/kyber#15]
Hello, I have issue with every installation, either it is apt or npm. None of them works properly. Anyone with the same issue or way to fix this?

`docker-compose build rdb
WARNING: The DOCKER_MACHINE_IP variable is not set. Defaulting to a blank string.
rdb uses an image, skipping
docker-compose build bdb-server
WARNING: The DOCKER_MACHINE_IP variable is not set. Defaulting to a blank string.
Building bdb-server
Step 1/13 : FROM python:3.6
3.6: Pulling from library/python
85b1f47fba49: Pull complete
ba6bd283713a: Pull complete
817c8cd48a09: Pull complete
47cc0ed96dc3: Pull complete
4a36819a59dc: Pull complete
db9a0221399f: Pull complete
7a511a7689b6: Pull complete
1223757f6914: Pull complete
Digest: sha256:59d8481f4b2d21f2ac6623e986b4e91fa704112df3e7d9dddbe7315d4a153ef5
Status: Downloaded newer image for python:3.6
 ---> 79e1dc9af1c1
Step 2/13 : LABEL maintainer "dev@bigchaindb.com"
 ---> Running in 1493d02d6fd5
 ---> 4449c5969463
Removing intermediate container 1493d02d6fd5
Step 3/13 : RUN apt-get update     && apt-get install -y vim     && pip install pynacl     && apt-get autoremove     && apt-get clean
 ---> Running in 62226e427746
Err http://deb.debian.org jessie InRelease
  
Err http://security.debian.org jessie/updates InRelease
  
Err http://deb.debian.org jessie-updates InRelease
  
Err http://security.debian.org jessie/updates Release.gpg
  Temporary failure resolving 'security.debian.org'
Err http://deb.debian.org jessie Release.gpg
  Temporary failure resolving 'deb.debian.org'
Err http://deb.debian.org jessie-updates Release.gpg
  Temporary failure resolving 'deb.debian.org'
Reading package lists...
W: Failed to fetch http://deb.debian.org/debian/dists/jessie/InRelease  

W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/InRelease  

W: Failed to fetch http://security.debian.org/dists/jessie/updates/InRelease  

W: Failed to fetch http://deb.debian.org/debian/dists/jessie/Release.gpg  Temporary failure resolving 'deb.debian.org'

W: Failed to fetch http://security.debian.org/dists/jessie/updates/Release.gpg  Temporary failure resolving 'security.debian.org'

W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/Release.gpg  Temporary failure resolving 'deb.debian.org'

W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package vim
ERROR: Service 'bdb-server' failed to build: The command '/bin/sh -c apt-get update     && apt-get install -y vim     && pip install pynacl     && apt-get autoremove     && apt-get clean' returned a non-zero code: 100
Makefile:4: recipe for target 'build' failed
make: *** [build] Error 1
`

EDIT: Fixed. problem was with proxy server I was behind

**Comment by ttmc** [comment]
This repository (bigchaindb/kyber) contains examples that worked with older versions of BigchainDB, but the stuff in this repository hasn't been maintained and the examples almost certainly won't work with newer versions of BigchainDB. Therefore we are closing all the old issues, marking the repo as old/not-supported, and archiving the repo. You can find newer examples in other places.
